version: "3"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.0.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  
  keycloak:
    image: docker.io/bitnami/keycloak:22.0.3
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_NAME=postgres
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_EXTRA_ARGS="--import-realm"
    depends_on:
      - postgresql
    volumes:
      - './filebrowser-realm.json:/opt/bitnami/keycloak/data/import/filebrowser-realm.json'

  filebrowser:
    image: docker.io/filebrowser/filebrowser:v2.25.0
    # user: $UID:$GID # Set these values beforehand
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./.filebrowser.json:/.filebrowser.json
    ports:
      - 80:8080
    # command: "/filebrowser config set --auth.method=noauth && /filebrowser"


    # TODO: add oauth2-proxy to connect keycloak and filebrowser https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak/
    # Or look at this solution: https://github.com/adyanth/portable-oidc/tree/main?tab=readme-ov-file
    #     Source: https://github.com/filebrowser/filebrowser/issues/1521
    

volumes:
  postgresql_data:
